version: '3'

services:

  mqtt:
    restart: always
    image: onesaitplatform/edge-mqtt:community
    container_name: edge-mqtt
    volumes:
      - /mosquitto/log
      - /mosquitto/data
    ports:
      - 1883:1883
    networks:
      edgenet:
        aliases:
          - mqtt

  database:
    restart: always
    image: fjahijado/onesaitplatform-edge-database:community
    container_name: edge-database
    environment:
      CONTAINER_TIMEZONE: Europe/Madrid
      INFLUXDB_SHARD_PRECREATION_ENABLED: 1
      MQTT_HOST: mqtt
      MQTT_PORT: 1883
      MQTT_TOPIC: topic/data
      INFLUXDB_DB: prometheus
    depends_on:
      - mqtt
    ports:
      - 5300:5300
      - 8086:8086
    networks:
      edgenet:
        aliases:
          - database

  cadvisor:
    restart: always
    image: google/cadvisor:latest
    container_name: edge-cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
    networks:
      edgenet:
        aliases:
          - cadvisor

  prometheus:
    restart: always
    image: fjahijado/onesaitplatform-edge-prometheus:community
    container_name: edge-prometheus
    ports:
      - 9090
    depends_on:
      - cadvisor
      - alertmanager
      - loselegidos
      - nodeexporter
      - database
    networks:
      edgenet:
        aliases:
          - prometheus

  loselegidos:
    restart: always
    build: ../sources/revolution-los-elegidos/target/
    image: fjahijado/onesaitplatform-edge-loselegidos:community
    container_name: edge-loselegidos
    ports:
      - 8080:8080
    networks:
      edgenet:
        aliases:
          - loselegidos

  alertmanager:
    restart: always
    image: prom/alertmanager:latest
    container_name: edge-alertmanager
    ports:
      - 9093
    networks:
      edgenet:
        aliases:
          - alertmanager

  nodeexporter:
    restart: always
    image: prom/node-exporter:latest
    container_name: edge-nodeexporter
    ports:
      - 9100
    volumes:
      - /:/rootfs:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
    networks:
      edgenet:
        aliases:
          - nodeexporter

  grafana:
    restart: always
    image: fjahijado/onesaitplatform-edge-grafana:community
    container_name: edge-grafana
    environment:
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_AUTH_BASIC_ENABLED=false
      - GF_AUTH_PROXY_ENABLED=false
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_NAME=Minsait
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Editor
    ports:
      - 3000:3000
    networks:
      edgenet:
        aliases:
          - grafana

networks:
  edgenet:
    driver: bridge
