{
 "title": "Aplicativos (spring-boot)",
 "tags": [
  "Prometheus",
  "grafana-ocp",
  "aplicativos",
  "springboot"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "application",
    "label": "Application",
    "query": "label_values(jvm_classes_loaded_classes,app)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(jvm_classes_loaded_classes{app=~\"$application\"}, instance)"
   },
   {
    "name": "hikaricp",
    "label": "HikariCP-Pool",
    "query": "label_values(hikaricp_connections{instance=~\"$instance\", app=~\"$application\"}, pool)"
   },
   {
    "name": "memory_pool_heap",
    "label": "Memory Pool (heap)",
    "query": "label_values(jvm_memory_used_bytes{app=~\"$application\", instance=~\"$instance\", area=\"heap\"},id)"
   },
   {
    "name": "memory_pool_nonheap",
    "label": "Memory Pool (nonheap)",
    "query": "label_values(jvm_memory_used_bytes{app=~\"$application\", instance=~\"$instance\", area=\"nonheap\"},id)"
   }
  ]
 },
 "panels": [
  { "title": "Memoria", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "process_uptime_seconds{app=~\"$application\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Heap vs Maximum",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 9, "x": 6, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{app=~\"$application\", instance=~\"$instance\", area=\"heap\", id=~\"$memory_pool_heap\"})/sum(jvm_memory_max_bytes{app=~\"$application\",instance=~\"$instance\", area=\"heap\", id=~\"$memory_pool_heap\"}) * 100"
    }
   ]
  },
  {
   "title": "Non-Heap vs Maximum",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{app=~\"$application\", instance=~\"$instance\", area=\"nonheap\", id=~\"$memory_pool_nonheap\"})/sum(jvm_memory_max_bytes{app=~\"$application\",instance=~\"$instance\", area=\"nonheap\", id=~\"$memory_pool_nonheap\"}) * 100"
    }
   ]
  },
  {
   "title": "Start time",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 6 },
   "format": "dateTimeAsIso",
   "valueName": "current",
   "targets": [
    {
     "expr": "process_start_time_seconds{app=~\"$application\", instance=~\"$instance\"}*1000"
    }
   ]
  },
  {
   "title": "Heap in use",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 9, "x": 6, "y": 6 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{app=~\"$application\", instance=~\"$instance\", area=\"heap\", id=~\"$memory_pool_heap\"})"
    }
   ]
  },
  {
   "title": "NON Heap in use",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 6 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{app=~\"$application\", instance=~\"$instance\", area=\"nonheap\", id=~\"$memory_pool_nonheap\"})"
    }
   ]
  },
  {
   "title": "JVM Heap",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{app=~\"$application\", instance=~\"$instance\", area=\"heap\", id=~\"$memory_pool_heap\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum(jvm_memory_committed_bytes{app=~\"$application\", instance=~\"$instance\", area=\"heap\", id=~\"$memory_pool_heap\"})",
     "legendFormat": "committed"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{app=~\"$application\", instance=~\"$instance\", area=\"heap\", id=~\"$memory_pool_heap\"})",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "JVM Non-Heap",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 11 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{app=~\"$application\", instance=~\"$instance\", area=\"nonheap\", id=~\"$memory_pool_nonheap\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum(jvm_memory_committed_bytes{app=~\"$application\", instance=~\"$instance\", area=\"nonheap\", id=~\"$memory_pool_nonheap\"})",
     "legendFormat": "committed"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{app=~\"$application\", instance=~\"$instance\", area=\"nonheap\", id=~\"$memory_pool_nonheap\"})",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "JVM Total",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 11 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{app=~\"$application\", instance=~\"$instance\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum(jvm_memory_committed_bytes{app=~\"$application\", instance=~\"$instance\"})",
     "legendFormat": "committed"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{app=~\"$application\", instance=~\"$instance\"})",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "GC Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 19, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(jvm_gc_memory_allocated_bytes_total{app=~\"$application\", instance=~\"$instance\"}[3m])",
     "legendFormat": "allocated {{application}} | {{instance}}"
    },
    {
     "expr": "rate(jvm_gc_memory_promoted_bytes_total{app=~\"$application\", instance=~\"$instance\"}[3m])",
     "legendFormat": "promoted {{application}} | {{instance}}"
    }
   ]
  },
  {
   "title": "GC Allocated (avg 30m)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 18 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "rate(jvm_gc_memory_allocated_bytes_total{app=~\"$application\", instance=~\"$instance\"}[30m])"
    }
   ]
  },
  {
   "title": "GC Promoted (avg 30m)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 22 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "rate(jvm_gc_memory_promoted_bytes_total{app=~\"$application\", instance=~\"$instance\"}[30m])"
    }
   ]
  },
  {
   "title": "Heap Memory Pools",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{instance=~\"$instance\", app=~\"$application\", id=~\"$memory_pool_heap\"}",
     "legendFormat": "Used -> {{id}}"
    },
    {
     "expr": "jvm_memory_committed_bytes{instance=~\"$instance\", app=~\"$application\", id=~\"$memory_pool_heap\"}",
     "legendFormat": "Commited -> {{id}}"
    },
    {
     "expr": "jvm_memory_max_bytes{instance=~\"$instance\", app=~\"$application\", id=~\"$memory_pool_heap\"}",
     "legendFormat": "Max -> {{id}}"
    }
   ]
  },
  {
   "title": "Non-Heap Memory Pools",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{instance=~\"$instance\", app=~\"$application\", id=~\"$memory_pool_nonheap\"}",
     "legendFormat": "Used -> {{id}}"
    },
    {
     "expr": "jvm_memory_committed_bytes{instance=~\"$instance\", app=~\"$application\", id=~\"$memory_pool_nonheap\"}",
     "legendFormat": "Commited -> {{id}}"
    },
    {
     "expr": "jvm_memory_max_bytes{instance=~\"$instance\", app=~\"$application\", id=~\"$memory_pool_nonheap\"}",
     "legendFormat": "Max -> {{id}}"
    }
   ]
  },
  {
   "title": "Process Open Files",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "process_files_open_files{app=~\"$application\", instance=~\"$instance\"}",
     "legendFormat": "Open Files"
    },
    {
     "expr": "process_files_max_files{app=~\"$application\", instance=~\"$instance\"}",
     "legendFormat": "Max Files"
    }
   ]
  },
  { "title": "Estadísticas HTTP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "Request Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "http_server_requests_seconds_count{instance=~\"$instance\", app=~\"$application\", uri!~\".*actuator.*\", uri!=\"/management/health\", uri!=\"/management/info\", uri!=\"/management/metrics\"}",
     "legendFormat": "{{method}} [{{status}}] - {{uri}}"
    }
   ]
  },
  {
   "title": "Response Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "http_server_requests_seconds_sum{instance=~\"$instance\", app=~\"$application\", uri!~\".*actuator.*\", uri!=\"/management/health\", uri!=\"/management/info\", uri!=\"/management/metrics\"} / http_server_requests_seconds_count{instance=~\"$instance\", app=~\"$application\", uri!~\".*actuator.*\", uri!=\"/management/health\", uri!=\"/management/info\", uri!=\"/management/metrics\"}",
     "legendFormat": "{{method}} [{{status}}] - {{uri}}"
    }
   ]
  },
  { "title": "Total de errores", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 } },
  {
   "title": "Global Error Count",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 63 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "expr": "tomcat_global_error_total{instance=~\"$instance\", app=~\"$application\"}"
    }
   ]
  },
  {
   "title": "Total Tomcat Error",
   "type": "graph",
   "gridPos": { "h": 4, "w": 21, "x": 3, "y": 63 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "tomcat_global_error_total{instance=~\"$instance\", app=~\"$application\"}",
     "legendFormat": "Total: {{app}}"
    }
   ]
  },
  {
   "title": "4XX Error Count",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 67 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(http_server_requests_seconds_count{app=~\"$application\", instance=~\"$instance\", status=~\"[4]..\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "Total Errors by HTTP code",
   "type": "graph",
   "gridPos": { "h": 4, "w": 21, "x": 3, "y": 67 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(http_server_requests_seconds_count{app=~\"$application\", instance=~\"$instance\",status=~\"[4-5]..\"}) by (status, app)",
     "legendFormat": "HTTP {{ status}} | {{app}}"
    }
   ]
  },
  {
   "title": "5XX Error Count",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 69 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(http_server_requests_seconds_count{app=~\"$application\", instance=~\"$instance\", status=~\"[5]..\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "log4j2 ALL (avg 30m)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 71 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "irate(log4j2_events_total{instance=~\"$instance\", app=~\"$application\"}[30m])",
     "legendFormat": "{{app}}->{{level}}",
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "title": "log4j2 Warn (avg 30m)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 78 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "irate(log4j2_events_total{instance=~\"$instance\", app=~\"$application\", level=~\"warn\"}[30m])",
     "legendFormat": "Warn -> {{app}}",
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "title": "log4j2 Error (avg 30m)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 85 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "irate(log4j2_events_total{instance=~\"$instance\", app=~\"$application\", level=~\"error\"}[30m])",
     "legendFormat": "Error -> {{app}}",
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "title": "log4j2 Fatal (avg 30m)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 92 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "irate(log4j2_events_total{instance=~\"$instance\", app=~\"$application\", level=~\"fatal\"}[30m])",
     "legendFormat": "Error -> {{app}}",
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  { "title": "HikariCP Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 99 } },
  {
   "title": "Active Connections",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 100 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "hikaricp_connections_active{instance=~\"$instance\", app=~\"$application\", pool=~\"$hikaricp\"}"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 100 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "hikaricp_connections_active{instance=~\"$instance\", app=~\"$application\", pool=~\"$hikaricp\"}",
     "legendFormat": "Active -> {{pool}}"
    },
    {
     "expr": "hikaricp_connections_idle{instance=~\"$instance\", app=~\"$application\", pool=~\"$hikaricp\"}",
     "legendFormat": "Idle -> {{pool}}"
    },
    {
     "expr": "hikaricp_connections_pending{instance=~\"$instance\", app=~\"$application\", pool=~\"$hikaricp\"}",
     "legendFormat": "Pending -> {{pool}}"
    }
   ]
  },
  {
   "title": "Connection Timeout",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 104 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "hikaricp_connections_timeout_total{instance=~\"$instance\", app=~\"$application\", pool=~\"$hikaricp\"}"
    }
   ]
  },
  {
   "title": "Connection Creation Time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 108 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "hikaricp_connections_creation_seconds_sum{instance=~\"$instance\", app=~\"$application\", pool=~\"$hikaricp\"} / hikaricp_connections_creation_seconds_count{instance=~\"$instance\", app=~\"$application\", pool=~\"$hikaricp\"}",
     "legendFormat": "Creation Time -> {{pool}}"
    }
   ]
  },
  {
   "title": "Connection Usage Time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 108 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "hikaricp_connections_usage_seconds_sum{instance=~\"$instance\", app=~\"$application\", pool=~\"$hikaricp\"} / hikaricp_connections_usage_seconds_count{instance=~\"$instance\", app=~\"$application\", pool=~\"$hikaricp\"}",
     "legendFormat": "Usage Time -> {{pool}}"
    }
   ]
  },
  {
   "title": "Connection Acquire Time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 108 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "hikaricp_connections_acquire_seconds_sum{instance=~\"$instance\", app=~\"$application\", pool=~\"$hikaricp\"} / hikaricp_connections_acquire_seconds_count{instance=~\"$instance\", app=~\"$application\", pool=~\"$hikaricp\"}",
     "legendFormat": "Acquire Time -> {{pool}}"
    }
   ]
  }
 ]
}