server:
  compression:
    enabled: true
    mime-types:
      - application/json
      - application/xml
      - text/plain
  port: ${SERVER_PORT:8080}
  context-path: /

management:
  security:
    enabled: false
  context-path: /actuator

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
    platform: org.hibernate.dialect.H2Dialect

